version: "3"
services:
  web:
    build:
      context: .
    image: pcdonation.azurecr.io/pc_donation:v0.1.9Th
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    ports:
      - 80:80
      - 5000:5000
    environment:
      NGINX_PORT: 80
    networks:
      - webnet

networks:
  webnet:
